source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, "9.0"

["Flashcard", "FlashcardTests"].each do | env |
    target env do
        
        pod 'Alamofire'        
        pod 'Gloss'
        pod 'FileKit'
        pod 'thenPromise'
        pod 'PKHUD', '~> 4.0'
        pod 'Eureka'
        pod 'RealmSwift'
        pod 'Morgan'
        pod 'SwiftyTimer'
        
        use_frameworks!
    end
end

